version: '3.9'
services:
  app:
    image: 'balancer'
    container_name: golang_container
    env_file:
      - .env
    tty: true
    build:
      context: .
    ports:
      - "8000:8080"
    depends_on:
      - db
    restart: on-failure

  db:
    image: 'postgres:13.1-alpine'
    container_name: db
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    ports:
      - '12345:5432'